consumption<-read.table("household_power_consumption.txt",sep=";",header=TRUE,stringsAsFactors=F, na.strings="?")
consumption$Date<-as.Date(consumption$Date,format='%d/%m/%Y')
head(consumption$Date)
consumption1<-subset(consumption,Date%in%as.Date(c("2007-02-01","2007-02-02")))
consumption1$DateTime=as.POSIXct(paste(consumption1$Date,consumption1$Time))
consumption1$Global_active_power<-as.numeric(consumption1$Global_active_power)
DateTime<-consumption1$DateTime
plot(x=DateTime,y=consumption1$Sub_metering_1,xlab="",type="l",ylab="Energy sub metering")
lines(x=DateTime,y=consumption1$Sub_metering_2,col="red")
lines(x=DateTime,y=consumption1$Sub_metering_3,col="blue")
legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2,legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()