consumption<-read.table("household_power_consumption.txt",sep=";",header=TRUE,stringsAsFactors=F, na.strings="?")
consumption$Date<-as.Date(consumption$Date,format='%d/%m/%Y')
head(consumption$Date)
consumption1<-subset(consumption,Date%in%as.Date(c("2007-02-01","2007-02-02")))
consumption1$DateTime=as.POSIXct(paste(consumption1$Date,consumption1$Time))
consumption1$Global_active_power<-as.numeric(consumption1$Global_active_power)
png("plot1.png", width=480, height=480)
hist(consumption1$Global_active_power,xlab="Global Active Power(kilowatts)",ylab="Frequency",main="Global Active Power",col="red")
dev.off()